### ISSUE TITLE
[task] [3p] Set up backend

### ISSUE THREAD

**Issue by boaanes** [boaanes/dat251-3#15]
**Task**
Setup a backend using firebase, with basic functionality.

---
## Todo

- [X] Set up firebase project  
- [X] Connect firebase SDK to flutter project
- [X] Verify that everything is working correctly
