### ISSUE TITLE
[task] [5p] Set up CI/CD pipeline

### ISSUE THREAD

**Issue by boaanes** [boaanes/dat251-3#17]
**Task**
We need to set up a CI/CD pipeline with github actions.
The goal is to run tests and then build and deploy to firebase.

---
## Todo

- [x] Set up testing facilities with flutter
- [x] Set up firebase deployment
- [x] Develop a github actions workflow for the pipeline itself
